{% set name = "stockwell" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stockwell-{{ version }}.tar.gz
  sha256: 11ccfe3c8b2f5a0e880f6bf5ef2df3b4c1a6e30130a36419e4ac715b5f69496f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
    - fftw
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - fftw

test:
  imports:
    - stockwell
  commands:
    - pip check
  requires:
    - pip
    - pytest
  commands:
    - pytest --pyargs stockwell

about:
  home: https://github.com/claudiodsf/stockwell
  summary: Time-frequency analysis through Stockwell transform
  license: CECILL-2.1
  license_file: LICENSE.txt
  description: |
    Python package for time-frequency analysis through Stockwell transform.
    Based on original code from NIMH MEG Core Facility
    (https://kurage.nimh.nih.gov/meglab/Meg/Stockwell).
  dev_url: https://github.com/claudiodsf/stockwell

extra:
  recipe-maintainers:
    - claudiodsf
